#!/usr/bin/env python3
# fs-uae-sync

import sys
import argparse
import os
import logging

import fsuaetools


def main():
  app = fsuaetools.App('launcher script for FS-UAE')

  # setup extra args
  parser = app.get_parser()
  parser.add_argument('-l', '--log-stdout', default=False, action='store_true',
                      help='FS-UAE logs to stdout')
  parser.add_argument('-x', '--extra-opts', default=[], action='append',
                      help='Pass-through FS-UAE options')
  parser.add_argument('fs_uae_config', nargs='?', default=None,
                      help='configuration to launch. must have .fs-uae file in Configurations')

  app.parse_args()
  app.setup()

  args = app.get_args()
  app.run(*args.extra_opts,
          cfg_file=args.fs_uae_config, log_stdout=args.log_stdout)

# ----- entry point -----
if __name__ == '__main__':
  sys.exit(main())
