#!/usr/bin/env python3
# fs-uae-cli

import sys
import argparse
import os
import subprocess

import fsuaetools as ft


wb_files = [
  'L/aux-handler',
  'C/Mount',
  'Devs/serial.device'
]

mountlist = [
  "AUX:",
  "Handler    = L:Aux-Handler",
  "StackSize  = 1000",
  "Priority   = 5"
]

startup_sequence = [
  "C:Mount AUX:",
  "newshell aux:"
]

fsuae_cfg = [
  "amiga_model = A4000/040",
  "window_hidden = 1",
  "floppy_drive_volume = 0"
]


def first_line_cb():
  if sys.platform.startswith('darwin'):
    path = os.path.dirname(os.path.realpath(__file__))
    subprocess.check_call(os.path.join(path, "iterm_focus"))


def main():
  app = ft.App('launcher script for running CLI commands with headless FS-UAE')

  # setup extra args
  parser = app.get_parser()
  parser.add_argument('-w', '--work-dir', default=None,
                      help='working directory')
  parser.add_argument('-r', '--wb-root', default=None,
                      help='root directory of Workbench 3.1 installation')
  parser.add_argument('-f', '--force', default=False, action='store_true',
                      help='force recreation of work dir')
  parser.add_argument('cmd', nargs='?', default=None,
                      help='command to launch')

  app.parse_args()

  # overwrite settings
  cfg = app.get_config()
  args = app.get_args()
  cfg.set_cli_work_dir(args.work_dir)
  cfg.set_cli_wb_root(args.work_dir)

  app.setup()

  # setup conio
  conio = ft.ConIOPty()
  shell = ft.Shell(conio, first_line_cb)
  fsuae_cfg.append("serial_port = " + conio.ttyname())

  # setup work dir
  wd = ft.WorkDir(cfg.get_cli_work_dir())
  fsuae_cfg.append("hard_drive_0 = " + wd.get_fs_root())

  # copy and create files
  wb_root = cfg.get_cli_wb_root()
  wd.copy_files(wb_root, wb_files)
  wd.create_mountlist(mountlist)
  wd.create_startup_sequence(startup_sequence)
  wd.create_fsuae_config(fsuae_cfg)

  try:
    app.start(cfg_file=wd.get_cfg_file_name())
    shell.run_loop()
  finally:
    app.stop()
    shell.close()
    conio.close()


# ----- entry point -----
if __name__ == '__main__':
  sys.exit(main())
